
general.live_config_reload = true

# themes from https://github.com/alacritty/alacritty-theme
general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml",
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[cursor]
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "On"

[env]
TERM="xterm-256color"

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[terminal.shell]
program = "/opt/homebrew/bin/bash"
args = ["-l"]

[selection]
save_to_clipboard = true

[window]
decorations = "None"
option_as_alt = "Both"

[window.padding]
x = 5
y = 0
